# Generated by Django 6.0.3 on 2026-03-10 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('house_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
                'db_table': 'house',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member'), ('guest', 'guest')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='house.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'House Member',
                'verbose_name_plural': 'House Members',
                'db_table': 'house_member',
                'unique_together': {('house', 'user')},
            },
        ),
    ]
