# Generated by Django 6.0.3 on 2026-03-11 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_housemember_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='emoji',
            field=models.CharField(default='🏠', max_length=10),
        ),
        migrations.AlterField(
            model_name='housemember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
