# Generated by Django 6.0.4 on 2026-04-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_house_emoji_alter_housemember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='join_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
