# Generated by Django 6.0.3 on 2026-04-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
        ('device', '0003_remove_electricaldevice_auto_cutoff_minutes_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='alert_event_house_i_d29d41_idx',
            old_name='alert_event_house_status_idx',
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='trigger_value',
            field=models.FloatField(blank=True, help_text='Actual value that triggered the alert (e.g. actual watts)', null=True),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Scope to a specific device (null = any device)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='device.electricaldevice'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='plug',
            field=models.ForeignKey(blank=True, help_text='Scope to a specific plug (null = all plugs in house)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='device.smartplug'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='threshold_value',
            field=models.FloatField(blank=True, help_text='Threshold value (watts for power rules, minutes for duration rules)', null=True),
        ),
    ]
