# Generated by Django 6.0.4 on 2026-04-25 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('house', '0005_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartplug',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugs', to='house.room'),
        ),
    ]
