# Generated by Django 6.0.4 on 2026-04-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_smartplug_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricaldevice',
            name='auto_cutoff_minutes',
        ),
        migrations.RemoveField(
            model_name='electricaldevice',
            name='risk_level',
        ),
        migrations.AddField(
            model_name='electricaldevice',
            name='until_alert_minutes',
            field=models.IntegerField(blank=True, help_text='Auto power-off after this many minutes of continuous use (null = disabled)', null=True),
        ),
        migrations.AddField(
            model_name='electricaldevice',
            name='until_cutoff_minutes',
            field=models.IntegerField(blank=True, help_text='Auto power-off after this many minutes of continuous use (null = disabled)', null=True),
        ),
        migrations.AddField(
            model_name='electricaldevice',
            name='until_notify_minutes',
            field=models.IntegerField(blank=True, help_text='Auto power-off after this many minutes of continuous use (null = disabled)', null=True),
        ),
        migrations.AddField(
            model_name='smartplug',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Whether the device is synced with the hardware registry'),
        ),
    ]
