# Generated by Django 6.0.3 on 2026-04-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_remove_electricaldevice_auto_cutoff_minutes_and_more'),
        ('house', '0006_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartplug',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plugs', to='house.house'),
        ),
    ]
