# Generated by Django 6.0.3 on 2026-04-25 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_smartplug_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidSmartPlug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plug_code', models.CharField(max_length=64, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('blacklist', models.BooleanField(default=False)),
            ],
        ),
    ]
