# Generated by Django 6.0.3 on 2026-04-25 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_validsmartplug'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartplug',
            name='active_uid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smartplug',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartplug',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartplug',
            name='relay_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartplug',
            name='rssi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartplug',
            name='uptime',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EnergyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watts', models.FloatField()),
                ('kwh', models.FloatField()),
                ('volts', models.FloatField()),
                ('amps', models.FloatField()),
                ('frequency', models.FloatField()),
                ('pf', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_logs', to='device.smartplug')),
            ],
        ),
    ]
