# Generated by Django 5.2.13 on 2026-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_smartplug_active_uid_smartplug_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricaldevice',
            name='device_type',
        ),
        migrations.AlterField(
            model_name='energylog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
