# Generated by Django 6.0.3 on 2026-04-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='energyreading',
            new_name='energy_read_plug_id_a60e9e_idx',
            old_name='energy_read_plug_id_idx',
        ),
        migrations.RenameIndex(
            model_name='energyreading',
            new_name='energy_read_device__28bcaf_idx',
            old_name='energy_read_device_id_idx',
        ),
    ]
